#!/bin/sh

set -e

BASEDIR="/mnt"
DIRNAME="alpine-chroot-$(basename "$(pwd)")"

abuild sanitycheck || exit 1

CHROOT="${BASEDIR}"/"${DIRNAME}"
[ -d "${CHROOT}" ] || \
	sudo alpine-chroot-create -c "${CHROOT}"

sudo -E -s alpine-chroot-abuild "${CHROOT}" $@
sudo alpine-chroot-destroy "${CHROOT}"
