#!/bin/sh
# Removes an existing alpine chroot.

set -e

if [ $# -ne 1 ]; then
	echo "USAGE: ${0##*/} CHROOT" 1>&2
	exit 1
fi

if [ $(id -u) -ne 0 ]; then
	echo "${0##*/} has to be started as root." 1>&2
	exit 1
fi

CHROOT="${1}"
for mountpoint in $(chroot "${CHROOT}" /bin/mount | cut -d ' ' -f3); do
	umount -l "${CHROOT}"/"${mountpoint}"
done

rm -rf "${CHROOT}"
