#!/bin/sh
# umount all mountpoints of an existing alpine chroot.

set -e

if [ $# -lt 1 ]; then
	echo "USAGE: ${0##*/} CHROOT..." 1>&2
	exit 1
fi

if [ $(id -u) -ne 0 ]; then
	echo "${0##*/} has to be started as root." 1>&2
	exit 1
fi

for chroot in $@; do
	for mountpoint in /dev /sys /run /proc; do
		busybox mountpoint -q "${chroot}/${mountpoint}" && \
			umount -l "${chroot}/${mountpoint}"
	done

	for mountpoint in $(mount | cut -d " " -f3 | grep "^${chroot}"); do
		umount -l "${mountpoint}"
	done
done
